import {
  ReceiptText,
} from "lucide-react";

import BillingStatusBadge from "./BillingStatusBadge";

import type {
  Bill,
} from "../types/billing.types";

interface Props {
  bill: Bill;
}

export default function BillDetails({
  bill,
}: Props) {
  return (
    <div className="rounded-xl border border-gray-200 bg-white">
      <div className="flex flex-col justify-between gap-4 border-b border-gray-200 p-6 md:flex-row">
        <div>
          <div className="flex items-center gap-2">
            <ReceiptText
              size={20}
              className="text-[#123B7A]"
            />

            <h2 className="text-xl font-bold text-gray-900">
              {
                bill.billNumber
              }
            </h2>
          </div>

          <p className="mt-2 text-sm text-gray-500">
            Complaint:{" "}
            {
              bill.complaintNumber
            }
          </p>
        </div>

        <BillingStatusBadge
          status={
            bill.status
          }
        />
      </div>

      <div className="grid gap-5 p-6 sm:grid-cols-2 lg:grid-cols-4">
        <Info
          label="Dealer"
          value={
            bill.dealer.name
          }
        />

        <Info
          label="Customer"
          value={
            bill.customer.name
          }
        />

        <Info
          label="Closure Type"
          value={
            bill.closureType
          }
        />

        <Info
          label="Generated By"
          value={
            bill.generatedBy
          }
        />
      </div>

      <div className="border-t">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[800px]">
            <thead className="bg-gray-50">
              <tr>
                {[
                  "Description",
                  "Qty",
                  "Rate",
                  "Amount",
                  "Tax",
                  "Total",
                ].map(
                  (heading) => (
                    <th
                      key={
                        heading
                      }
                      className="px-5 py-3 text-left text-xs font-semibold uppercase text-gray-500"
                    >
                      {heading}
                    </th>
                  )
                )}
              </tr>
            </thead>

            <tbody className="divide-y">
              {bill.lineItems.map(
                (item) => (
                  <tr
                    key={
                      item.id
                    }
                  >
                    <td className="px-5 py-4 text-sm text-gray-800">
                      {
                        item.description
                      }
                    </td>

                    <td className="px-5 py-4 text-sm">
                      {
                        item.quantity
                      }
                    </td>

                    <td className="px-5 py-4 text-sm">
                      ₹
                      {
                        item.rate
                      }
                    </td>

                    <td className="px-5 py-4 text-sm">
                      ₹
                      {
                        item.amount
                      }
                    </td>

                    <td className="px-5 py-4 text-sm">
                      ₹
                      {
                        item.taxAmount ??
                        0
                      }
                    </td>

                    <td className="px-5 py-4 text-sm font-semibold">
                      ₹
                      {
                        item.totalAmount
                      }
                    </td>
                  </tr>
                )
              )}
            </tbody>
          </table>
        </div>
      </div>

      <div className="flex justify-end border-t p-6">
        <div className="w-full max-w-sm space-y-3">
          <AmountRow
            label="Subtotal"
            value={
              bill.subtotal
            }
          />

          <AmountRow
            label="Tax"
            value={
              bill.taxAmount
            }
          />

          <div className="border-t pt-3">
            <AmountRow
              label="Total"
              value={
                bill.totalAmount
              }
              strong
            />
          </div>
        </div>
      </div>
    </div>
  );
}

function Info({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div>
      <p className="text-xs text-gray-500">
        {label}
      </p>

      <p className="mt-1 text-sm font-medium text-gray-900">
        {value}
      </p>
    </div>
  );
}

function AmountRow({
  label,
  value,
  strong = false,
}: {
  label: string;
  value: number;
  strong?: boolean;
}) {
  return (
    <div className="flex justify-between">
      <span
        className={
          strong
            ? "font-semibold text-gray-900"
            : "text-sm text-gray-500"
        }
      >
        {label}
      </span>

      <span
        className={
          strong
            ? "text-lg font-bold text-gray-900"
            : "text-sm font-medium text-gray-800"
        }
      >
        ₹
        {value.toLocaleString(
          "en-IN"
        )}
      </span>
    </div>
  );
}